### ISSUE TITLE
Thank you & a request

### ISSUE THREAD

**Issue by sfjeis** [Botbang/avro-bangla-autocorrect-dictionary#1]
Thanks a lot for your work and thanks a lot to the people who compiled this autocorrect dictionary. Thanks to this work, spelling mistakes in Bangla will be reduced by a lot.

I have found that -
1. Bangla proofing tools from Microsoft Office / Editor from Office 365 (online) is totally very inaccurate for Bangla spell checking.
2. Google Docs is much better but still makes mistakes. I am guessing Googles AI is still learning from user data and it will get much better very soon. If only there were an "Online Google spell checker" add-on for MS Word! (because Google Docs is not a good word processor).
3. Lastly Avro spell checker / autocorrect is getting better because of contribution from people like you. Avro itself is the only viable option for the time being for spell check / autocorrect.

I have a request. Can you please include the entries found in the " সরকারি কাজে প্রমিত বাংলা ব্যবহারের নিয়ম - ২য় সংস্করণ " in the following link? -  [ THE LINK](http://www.bfri.gov.bd/site/page/4b5a4011-3571-4bea-bf0c-a9fd973871ec/সরকারি-কাজে-প্রমিত-বাংলা-ব্যবহারের-নিয়ম)

It would enrich the dictionary even more! And it would really be a great help for documentation works in offices.
Thank you again.

**Comment by afnan-hossain** [comment]
Hey! @sfjeis,
Thanks for noticing, you're literally the first one to appreciate this project tbh! This project is actually based on "সরকারি কাজে প্রমিত বাংলা ব্যবহারের নিয়ম" from the beginning. But it's not complete as you can see. Thanks for the suggestion anyway, I'll definitely try to add the rest of the words. 

Have a good day!

**Comment by rahaaatul** [comment]
Is this project abandoned? 

By the way, a shameless plug, I have created skins for avro [here](https://github.com/rahaaatul/Skins-for-Avro). I'll be making more in the future, if anyone's looking for sleek themes.
