### ISSUE TITLE
suggestion 

### ISSUE THREAD

**Issue by 2u841r** [Botbang/avro-bangla-autocorrect-dictionary#2]
Please consider adding SSC, HSC, GPA, BSc, MSc, PhD, BCS, and other academic words.
also NPSB, EFT, BEFTN, RTGS, MFS, and other banking and payment related words.
TB, HIV, OCD, PTSD, ADHD, illness /medical / diagnostic terms.

Thanks.

**Comment by afnan-hossain** [comment]
added, thanks!
